import React from 'react';
import { Bar } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const SalesReports = () => {
  const salesPerformanceData = {
    labels: ['Product A', 'Product B', 'Product C', 'Product D'],
    datasets: [
      {
        label: 'Sales Performance',
        data: [12, 19, 3, 5],
        backgroundColor: [
          'rgba(255, 99, 132, 0.2)',
          'rgba(54, 162, 235, 0.2)',
          'rgba(255, 206, 86, 0.2)',
          'rgba(75, 192, 192, 0.2)',
        ],
        borderColor: [
          'rgba(255, 99, 132, 1)',
          'rgba(54, 162, 235, 1)',
          'rgba(255, 206, 86, 1)',
          'rgba(75, 192, 192, 1)',
        ],
        borderWidth: 1,
      },
    ],
  };

  return (
    <div className="p-4">
      <h2 className="mb-4">Sales Reports Overview</h2>

      <div className="card mb-4">
        <div className="card-header">Filters</div>
        <div className="card-body">
          <form className="row g-3 align-items-center">
            <div className="col-md-4">
              <label htmlFor="reportType" className="form-label visually-hidden">Report Type</label>
              <select id="reportType" className="form-select" defaultValue="Choose Report Type...">
                <option disabled>Choose Report Type...</option>
                <option>Sales Performance by Product</option>
                <option>Sales by Region</option>
                <option>Customer Acquisition Cost</option>
              </select>
            </div>
            <div className="col-md-3">
              <label htmlFor="dateRange" className="form-label visually-hidden">Date Range</label>
              <input type="text" className="form-control" id="dateRange" placeholder="Date Range" />
            </div>
            <div className="col-md-3">
              <label htmlFor="salesPerson" className="form-label visually-hidden">Sales Person</label>
              <input type="text" className="form-control" id="salesPerson" placeholder="Sales Person" />
            </div>
            <div className="col-md-2">
              <button type="submit" className="btn btn-primary w-100">Apply Filters</button>
            </div>
          </form>
        </div>
      </div>

      <div className="row mb-4">
        <div className="col-12">
          <div className="card">
            <div className="card-header">Sales Performance Chart</div>
            <div className="card-body" style={{ height: '400px' }}>
              <Bar data={salesPerformanceData} options={{ maintainAspectRatio: false }} />
            </div>
          </div>
        </div>
      </div>

      <div className="card">
        <div className="card-header">Detailed Sales Data</div>
        <div className="card-body">
          <div className="table-responsive">
            <table className="table table-hover mb-0">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Report Name</th>
                  <th>Generated By</th>
                  <th>Value</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>2024-02-15</td>
                  <td>Q4 2023 Performance</td>
                  <td>Admin</td>
                  <td>$500,000</td>
                  <td><button className="btn btn-sm btn-outline-primary">View</button></td>
                </tr>
                <tr>
                  <td>2024-01-20</td>
                  <td>Jan 2024 Leads</td>
                  <td>Admin</td>
                  <td>250 Leads</td>
                  <td><button className="btn btn-sm btn-outline-primary">View</button></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SalesReports;
